// Hey! These are my solutions to the problems found on ProjectEuler.net. I have tried to make them as concise as possible, but feel free to email me suggestions! -- Ben -- bphaaland@gmail.com

// Problem Sets

// Problem One -- 
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

var counter = 0;

function sumOfDivisibles(x,y,max){  // creates a function with the parameters (divisible by x, divisible by y, max number tested)
  for(i=0;i<max;i++){
    if((i%x==0)||(i%y==0)){         // if x is divisible by x OR if it is divisible by y then add it to an arbitrary counter
      counter += i;
    }
  }
  debug(counter)
}

sumOfDivisibles(3,5,10);            // console logs 23


// Problem Two --
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var x = 1;
var y = 2;
fiboSum = 0;

function fiboSumEven(max){
  for(i=0;i<max;i++){        // this loop recreates the Fibonacci sequence
    z = x;
    x = y;
    y += z;
    
    if(z>=4000000){          // if the the Fibonacci sequence value exceeds four million, jump out of the loop
    	break; 
    }
    
    else if(z % 2==0){       // else decide if that bad boy is even or not
  	fiboSum += z;            // if they are even add them together
  	}
  }
  debug(fiboSum);
}

fiboSumEven(10);             // console logs 44



// Problem Three --
// The prime factors of 13195 are 5, 7, 13 and 29.
// What is the largest prime factor of the number 600851475143 ?




// Problem Four --
// A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
// Find the largest palindrome made from the product of two 3-digit numbers.




// Problem Five --
// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

var testNumber = 0;

for(i=0;i<=1000000000;i++){
  if ((i % 2 == 0) &&
      (i % 3 == 0) &&
      (i % 4 == 0) &&
      (i % 5 == 0) &&
      (i % 6 == 0) &&
      (i % 7 == 0) &&
      (i % 8 == 0) &&
      (i % 9 == 0) &&
      (i % 10 == 0) &&
      (i % 11 == 0) &&
      (i % 12 == 0) &&
      (i % 13 == 0) &&
      (i % 14 == 0) &&
      (i % 15 == 0) &&
      (i % 16 == 0) &&
      (i % 17 == 0) &&
      (i % 18 == 0) &&
      (i % 19 == 0) &&
      (i % 20 == 0)) {
    debug(i);                // console logs 232792560
  } 
}










var primeList = [1,2];
var n = 100;

for(i=3;i<=n;i+=2) {
  primeList.push(i);
}

// for(i = primeList.length - 1; i >= 0; i--) {
//     if(primeList[i] === "x") {
//        primeList.splice(i, 1);
//     }
// }

debug(primeList);


// Example
// create an array with all the numbers out to 100
// start at 2, multiply 2 by all the factors up to half of 100
// remove all those numbers out of the array
// find the first number in the array that is not 1
// multiply that number by 2 through 100 and take those out of the array
// etc..etc..



  // if(i % 2 == 0){
  //   primeList.slice(i, 1);
  // }
  // else if(i % 3 == 0) {
  //  primeList.slice(i, 1);
  // }
  // else if(i % 5 == 0) {
  //  primeList.slice(i, 1);
  // }
  // else if(i % 7 == 0) {
  //  primeList.slice(i, 1);
  // }
  // else if(i % 11 == 0) {
  //  primeList.slice(i, 1);
  // }
  // else {
  //  primeList.push(i);
  // }


// Initially, let p equal 2, the first prime number.
// Starting from p, enumerate its multiples by counting to n in increments of p, and mark them in the list (these will be 2p, 3p, 4p, etc.; the p itself should not be marked).

var array = [2, 5, 9, 9, 9, 6, 9];
var index = array.indexOf(9);


if (index > -1) {
    array.splice(index, 100000);
}

debug(array);


// Problem Five --
// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

var testNumber = 0;

for(i=0;i<=1000000000;i++){
  if ((i % 20 == 0) &&
    (i % 19 == 0) &&
    (i % 18 == 0) &&
    (i % 17 == 0) &&
    (i % 16 == 0) &&
    (i % 15 == 0) &&
    (i % 14 == 0) &&
    (i % 13 == 0) &&
    (i % 12 == 0) &&
    (i % 11 == 0)) {
    debug(i);
  } 
}
















